### ISSUE TITLE
Summary output

### ISSUE THREAD

**Issue by justinjee** [justinjee/proScatter#5]
Currently prints no. unique links in each experiment, as well as no. unique links in the intersection of the experiments.

Will try:
-Sliding window correlation
-Printing unique points as well as intersections?

**Comment by KKescondida** [comment]
Hi J,
I get the following error when I try to run proScatter on EC, Core and an xwalk file (from a model of only UvrD ie. no RpoB or RpoC points): 

Summary for RpoC-RpoC
    EC:  72
    Core:  231
Traceback (most recent call last):
  File "proScatter.py", line 140, in <module>
    proscatter.print_summary()
  File "proScatter.py", line 69, in print_summary
    points = set(interaction[key])
KeyError: 'RpoC-RpoC'

When I change the fasta file so it only contains UvrD, there's no error. So I think there's a small bug when one of the data directories does not contain at least 1 xlink from all the proteins?

K
